server:
  port: 8084

spring:
  application:
    name: user-service
    mongodb:
      uri: mongodb://localhost:27017/user_db

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus