package com.microservices.shipping_service;

import com.microservices.shipping_service.dto.CreateShipmentRequest;
import com.microservices.shipping_service.dto.CreateShipmentResponse;
import com.microservices.shipping_service.model.ShipmentModel;
import com.microservices.shipping_service.model.ShipmentStatus;
import com.microservices.shipping_service.model.ShippingAddress;
import com.microservices.shipping_service.repo.ShipmentRepository;
import org.springframework.stereotype.Service;

import java.time.Instant;

@Service
public class ShippingService {

    private final ShipmentRepository repo;

    public ShippingService(ShipmentRepository repo) {
        this.repo = repo;
    }

    public CreateShipmentResponse create(CreateShipmentRequest req) {

        // ✅ Idempotency: one shipment per orderId
        var existing = repo.findByOrderId(req.getOrderId());
        if (existing.isPresent()) {
            return toResponse(existing.get());
        }

        ShipmentModel s = new ShipmentModel();
        s.setOrderId(req.getOrderId());
        s.setUserId(req.getUserId());
        s.setStatus(ShipmentStatus.CREATED);

        ShippingAddress addr = new ShippingAddress();
        addr.setHouseNum(req.getShippingAddress().getHouseNum());
        addr.setCity(req.getShippingAddress().getCity());
        addr.setState(req.getShippingAddress().getState());
        addr.setZip(req.getShippingAddress().getZip());
        addr.setCountry(req.getShippingAddress().getCountry());
        s.setShippingAddress(addr);

        Instant now = Instant.now();
        s.setCreatedAt(now);
        s.setUpdatedAt(now);

        // ✅ trackingId (_id) is generated by Mongo automatically if trackingId is null
        s = repo.save(s);

        return toResponse(s);
    }

    private CreateShipmentResponse toResponse(ShipmentModel s) {
        CreateShipmentResponse res = new CreateShipmentResponse();
        res.setTrackingId(s.getTrackingId());
        res.setOrderId(s.getOrderId());
        res.setUserId(s.getUserId());
        res.setStatus(s.getStatus());
        return res;
    }
    public java.util.Optional<ShipmentModel> getByTrackingId(String trackingId) {
        return repo.findById(trackingId);
    }
}