server:
  port: 8085

spring:
  application:
    name: shipping-service
    mongodb:
      uri: mongodb://localhost:27017/shipping_db

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus